### ISSUE TITLE
🐛 [BUG] - The next and previous buttons are not functioning.

### ISSUE THREAD

**Issue by antenehbedilu** [master-8702/master_media_player#11]
+ Following the addition of a new song to the playlist, the __next__ and __previous__ buttons do not appear.
### Before
![photo_2023-09-04_23-20-55](https://github.com/master-8702/master_media_player/assets/45298436/950bf9fe-1089-4f05-8e56-8d3a83d8e34a)

### After *- reopening playlist.*
![photo_2023-09-04_23-20-58](https://github.com/master-8702/master_media_player/assets/45298436/4c039ca0-5a96-415d-aab4-956a4eb154cf)

**Comment by master-8702** [comment]
#12 
fixed
